name: analisis
channels:
- conda-forge
- nodefaults
dependencies:
- python==3.9
- cython==0.29.32
- matplotlib==3.5.2
- pandas==1.4.3
- numpy==1.23.1
- plotly==5.9.0
- scikit-learn==1.1.1
- jupyter==1.0.0
- pip==22.2.1
- pip:
  - tensorflow==2.9.1
  - tensorflow-cpu==2.9.1
  - pygad==2.17.0
  - xgboost==1.7.4